#+title: cse170 - Personal project User Manual (Prove 05)
#+AUTHOR: Daniel Gomez


Chapter 2 of the User Manual


This week we are spending time working on Chapter 2 of the User Manual. This is based off Design your Life by Dill Burnett and Dave Evan from Stanford.


* Where are you?
Take 5-10 minutes and define Health, Work, Play, and Love.
Using a dashboard scale of 0, ¼, ½, ¾, full, rate yourself.
Ask yourself if there’s a design problem you’d like to tackle in any of these areas.
Now ask yourself if the ”problem” is a gravity problem, or is in your circle of influence.


* Making a Compass – Defining Workview and Lifeview
Write a short reflection about your Workview. (100-250 words)
Address critical issue related to what work is and what it means to you.
More than a list but a statement of your view of work
* Reflections Questions
Why work
What’s work for?
What does work mean?
How does it relate to the individual, others, and society?
What does money have to do with it?
What do experience, growth, and fulfillment have to do with it?
Write a short reflection about your Lifeview (100-250 words)
Critical defining values and perspectives provide the basis for your understanding of life.
Matters of ultimate concern matter most to you.
Reflection Questions
Why are we here?
What is the meaning or purpose of life?
What are the relations between individuals and others?
Where do family, country, and the rest of the world fit in?
What is good, and what is evil?
Is there a higher power, God, or something transcendent, and if so, what impact does this have on your life?
What is the role of joy, sorrow, justice, injustice, love, peace, and strife in life?
Ask these questions
Where do your view on work and life complement one another
Where do they clash?
Does one drive the other? How?


 

  

  Keep a Good Time Journal

  Complete a log of your daily activities this week, that engage you or that provide you energy, and contrast those that don’t.
  At the end of the week jot down your reflections.
  Are there any surprises?
  Add Historical Data: Review the past month to year on activities that you have done that give you energy or engagement, and those that don’t.
   

    

    2nd Class period

    Keep a Good Time Journal – Part 2

    Analysis your data, figure out what does or does not engage and energize you. Use AEIOU method to help
    Activities What was it? Structured/Unstructured? Role?
    Environments Where was it? Effects? When? Feelings?
    Interactions People or Machines? Familiarity? Formal/Informal?
    Objects Tools? Equipment? Inspiration? Devices?
    Users Who and their role? Positive or Negative? Contributed?
     

     Mind Map

     Mind mapping is a great tool for ideating by yourself or in a group. Mind mapping works by using the free association of words, one after another, to open up the idea space and come up with new solutions. It bypasses your inner logical/verbal censor.
     Review your Good Time Journal, Choose three activities, one that
     Engagement: Felt you were engaged?
     Energy: Highly energizing?
     Flow: Brought you in the flow?
     Create a mind map (2-3 layers and secondary connections), For each map
     Look at our layers, and pick three things that jump out.
     Create a job description for each
     Create a role for each job description. Draw/Find a pic/meme
      

      Odyssey Plan

      Create three alternative five-year plans.
      Three plans
      Odyssey Plan 1: Life One: That Thing that you Do
      Odyssey Plan 2: Life Two: That Thing that you’d do if thing one were suddenly gone
      Odyssey Plan 3: Life Three: The thing you you’d do or the Life you live If money or image were no object.
      Six columns
      Year 0: This is your starting point: i.e. Now or After Grad,
      Year 1: Column 2: One year from now
      Year 2-5: Remaining columns, next 4 years.
      Give the Odyssey Plan a Title: six words max
      Write three questions that arise out of each one
      A good designer asks questions to test assumptions, reveal insights, check timelines, and look for possibilities. What do you want to test and explore about your Odyssey? 2-3 Questions
      Indicate dashboard gauge: Puts some measurements on the plan.
      0-100%
      Resources: time, money, skill, contacts
      Likability: hot or cold, excited/apathetic.          
      Confidence: valid/verify, uncertain/feasible
      Coherence: make sense, match work/life views
      Present/Share your plan
       

       What is expected for Chapter 2?

       Health, Work, Play, and Love Dashboard
       Define, Measure, Analysis, Summary
       Workview and Lifeview Compass
       Value Statement for each
       Good Time Journal Entries
       10-20 entries (Past or Present)
       3 Mind Maps
       Engagement, Energy, Flow
       Odyssey Plans
       Plan A, B, and Unlimited
