#+title: cse170 - Personal project User Manual (Prove 05)
#+AUTHOR: Daniel Gomez
#+DATE:


* What is your style?
I like to get things done. I like to speculate. I like to have fun. But mostly I like to surround myself around the philosophy of doing, and planning on how. A work habit I have is to spend some time planning on the most efficient way I can get the job done, and make sure that I don't have to work hard, /but work smart/.

* When do you like people to approach you and how?
I like it when people approach me quietly and predictably. I don't like to be caught by suprise. A possible weakness I see in this: that's not exactly how life works, and often times I can't be catered this way for my own convenience.

* What do you value?
I value knowledge over people and possessions. I value knowledge to highest regard. Anything I can do to invest in the sustaining of opportunity. People and possessions are a result of knowledge. A nice advantage to this mindset is the constant learning and growth one can acquire.

* How do you like people to communicate with you?
I like when they approach me with a query or a demand formally, but in a way that I'm in a position to reject it if I want to. Phone calls are nice because they are brief and get straight to the point of information. Texting is one of the worst because the information is usually delayed that way and communication isn't as fast.

* How do you make decisions?
I try to make decisions formally and methodically, but if I'm in a pinch I have no problem accepting that and doing what I need to get the work done. The biggest priority is to get the work done, and set myself up so there's less of it in the future.

* How can people help you?
They can help me by alleviate stress. Any help that requires me to *help them* is of no help to me.
People can also help me by providing a use, whether that be with their presence, or offered by useful information and roles

* What will you not tolerate in others?
I won't tolerate any unfairness and mistreatment of the minority. I also won't tolerate people's emotions getting in the way of decisions, or doing things just because it 'feels right'. Although that may be a satisfying benchmark, it doesn't really help making effective decisions.

* Take another hour or so and add some depth to round it out. Refer to the results of the personality test you completed in preparation for this lesson. Pay special attention to the strengths and weaknesses and work habits explanations of your results.

Take no more than an hour to answer the following questions with the first thing that comes to mind:
Formatting
You may format your document in whatever way seems attractive to you as long as it conforms to the following minimum requirements.
The title should be your name.
The following sections must be included:
My style
What I value
What I don't have patience for
How best to communicate with me
How to help me
What people misunderstand about me


*My personality type is Architect INTJ-A/INTJ-T*
A lot of villains are modeled after it.
+Shared personality with Walter White Eisenberg and Arnold Schwartzenegger.+
