#+author: Daniel Gomez
#+title: cse170: Week 10 Reflection
* Points Earned: 100/100
* 5 pts Questions             Affect: (What?, So What?...Return, Report, Reflect and Regroup.)
* What? (Return and Report)
* What did I do to prepare for class this week?
I did all of the assigned reading and researched all of the topics, including completing the personality test
* What evidence can I provide that demonstrates with affirmation statements?
My response to the following.
* What concept from this week are you uncertain of or would like to know more about?
None.
* What topics were studied this week, and what are their definitions?
Definitions for professional communication, ethical communication, ten basic principles behind making virtual teamswork function.
* What phase of your projects did you complete?
We completed the next activity for our Acorn project, and I was added to a new group where I needed to contribute to something new to activities already done.
* In your team meeting, what where the answers to this week’s questions?
The four points of practical leaership: Organization, Communication, Teaching, and Personal Leadership
* Summarize this week’s scenerio?
This week's scenario focused on a dysfunctional software team between Astrid, Govind, and Rita. Astrid was very apprehensive about Govind and his behavior, but as they got to know eachother and treat eachother respctively, they became an efficient team.
* Where did you put your assigments in GitHub?
On this github page
* So What? (Reflect and Regroup)
* What did I learn from the study material
I learned that even thought sometimes you might (even naturally) clash with coworkers due to differences, being patient with one-another will allow you to pair with anyone, and therefore become a great asset.
* Why is this week's topic important?
It's important because conflict will occur naturally and very often in the workplace, so it's important you know how to deal with it so it doesn't become such an impeding process.
* How did this week scenerio relate to the week’s topic?
Since this week we focused on 'kind leadership' or, leadership 'with a small l', it was very fitting to have studied and read a scenario of a software team that tried to get past each other's differences by virtue of patience and kindness.
* What did you learn from your work on your project?
This week as we attended the career fair, I learned that planning for a job and internship can never be too-soon. We can start at virtually any time. In fact, for Software Engineers, after CSE310 specifically, we will be ready as-per the school's strong opinion.
* What insights did your team lean from this week’s questions?
We were able to discuss ways in which we could lead without being in a position of authority.
* What actions were assigned to you, in your team meeting?
Attend the next career fair on campus.
* 10 pts Questions Behavior: (What now?...my ideas are starting to emerge!)
* What is the most significant take-a-way you have gained from your study this week?
A significant take-a-way: the best way to be influential in the workplace is by making sure I'm constantly and always living in a way that is inspiring. 
* What do you do, steps, or processes related to this week's topic?
I seek to live more honestly and with more integrity even when not being watched directly. That way interviewers will be able to differentiate me from those who are not, and may make a judgement to hire me.
* How would you explain this week's topics to a person not in this class?
This week we focused on ways in which we could become better leaders, even if we didn't have specific rule over people or an organization. Thus, in a way, becoming better stewards over the things that we own and oversee. That way we possibly show the Lord that we may be trusted with more.
* What did you learn by explaining this week's topic to someone not in this class?
I learned that this was a highly-agreeable topic and take. The person I shared it to also really enjoyed sharing what he thought leadership and stewardship meant for the layperson.
* Write a SMART goal for next week?
Complete a type-racer on sudden death mode every day this week
Mark my todo-list when done, with a goal to reach 50wpm by the end of this week.
* What would you do differently next week?
I would make sure to be more consistent and do this first thing in the morning, and also incorporating an alarm to do-so.
* What five take did you get from the scenerio?
My five-take was looking back on my mission and remembering having some companions and people that I found difficult to agree with, or at least ones that I didn't find myself naturally attracted to be around in a friendly-sense. But like Astrid and Rita, It's important to put those differences aside even if they may bother us to our metaphorical cores.
* How does the weekly topic relate to the MIM model?
The MIM model works great in this scenario because it really takes patience to process what happens that may happen to us, and taking a minute to process and react in order to make sure we don't do or say things we might regret.
* 20 pts Questions Cognitive: (Wow, I learn?... Ok that is deep!)
* Why is this week's topic important for teamwork?
I found this week's topic was crucial for teamwork because in reality most of life's problems can't be tackled on our own, at least not any problems of substantial impact. We need to work with others who /will/ have more of a knowledge than we do in a topic (we all ultimately will encounter somebody like that). We'll find that we might not always be compatible or easy to work with for us.
* How do plan on contributing to the team, besides completing your tasks?
I plan on reaching out and getting to know the individual members of my newly-assigned team.
* How does your experience relate to other experiences you have had?
My experience serving a full-time mission really help me realize more-so that each of us were all in fact very different. Some missionaries even expressed strong Progressive political viewpoints and some their more Libertarian. But the work was what in fact pulled us together to achieve a common goal.
* How does your experience relate to other classmates’ experiences?
Many of us hold extreme differences in background and culture, and in spite of all those differences, Christ and his work brings us together to be nice to one another.
* Tell me about what you taught someone? And what did they learn, that they didn’t know before?
I taught someone about morals and the importance of moral-discipline. They didn't really understand the purpose of being morally straight, and they learned more about the Gospel of Jesus Christ in the process.
* If you were to write your experience as STAR story, how would you phrase it?
When I taught somebody about moral-discipline on my 2-year mission, they seemed confused because they claimed that good-behavior and justice was relative to the individual's upbringing. While I affirmed that some of those things were in fact true, the Gospel of Jesus Christ affirms us that there will always be an innate and if not innate, a true right and a wrong that we need to follow and execute. It only befits us doing so.
* If this was a religion class, how would you relate this week’s topic to the gospel?
I found that this week's topic was easy to relate to the gospel because I could always refer to what kind of leader Jesus Christ was. He never used his leadership and power to berate another human being, or assert dominance. He used it to enable people and change people's lives, and I supposed while reading the scenario, for that purpose are we to use leadership or even in a layperson team-member role. 
