#+title: Week6_reflection

Reflection        Name: Daniel Gomez
Total Points 100/100

Every other week in this class, you will reflect on your learning. Your participation in the summary is a summation of your answers the following questions. The questions are categorized on the difficulty of depth. Each question you answer is worth that many points; when you are done answering the questions, give yourself a total score based on the rubrics and provide justification in one sentence. You can only use each question once.

Please answer a subset of the following questions:

5 pts Questions             Affect: (What?, So What?...Return, Report, Reflect and Regroup.)
What? (Return and Report)

* What did I do to prepare for class this week?
This week I completed all of the necessary activities and readings
* What evidence can I provide that demonstrates with affirmation statements?
The accuracy of information answered throughout the following questions
* What concept from this week are you uncertain of or would like to know more about?
I not unfamiliar with any topic.
* What topics were studied this week, and what are their definitions?
We went more in depth about our user manuals, and finalized them.
* What phase of your projects did you complete?
I completed all.
* In your team meeting, what where the answers to this week’s questions?
Is the user manual neatly formatted and readable?
Yes, mine was.
Is it well written and fully understandable?
Yes, it is.
Is it consistent with what you know of that person so far?
Yes I am.
Is there enough information to improve how you might work with that person in the future?
They wanted more information, and so now I need to supply with more.

* Summarize this week’s scenerio?
Our scenario was to review our team's personal user manuals.
* Where did you put your assigments in GitHub?
Posted in the README and link shared with the teacher
* So What? (Reflect and Regroup)
* What did I learn from the study material
* Why is this week's topic important?
Like last week's, this week's topic is important because if we work on being professional now, we will hopefully develop a mastery for the future. We also reviewed what we had in our drafts individually with our teamates.
* How did this week scenerio relate to the week’s topic?
The whole purpose of a user manual is to share it with others so they may get to effectively understand you and get to know you.
* What did you learn from your work on your project?
I learned that although I though my project was complete, there was still a lot to be improved upon so it may have been more comprehensible.
* What insights did your team lean from this week’s questions?
We had more of an idea how other people may have interpreted the question's differently.
* What actions were assigned to you, in your team meeting?
Work on criticism and feedback to produce a final draft.
* 10 pts Questions Behavior: (What now?...my ideas are starting to emerge!)
* What is the most significant take-a-way you have gained from your study this week?
The most significant take-a-way was that as teammates we need to have more effective communication so we could decide on a time to meet.
* What do you do, steps, or processes related to this week's topic?
I sought out to read my document top to bottom, and then changes as I go.
* How would you explain this week's topics to a person not in this class?
I would explain it similarly as I did last week: Professionalism refers to the way you represent yourself in a business setting. Most of all, professional behavior is considerate, formal, and focused.
* What did you learn by explaining this week's topic to someone not in this class?
I explained the concept of proof-reading a draft.
* Write a SMART goal for next week?
Finish 2 type racers with the 'sudden death' setting at 60wpm.
* What would you do differently next week?
I would just attempt these casually over time.
* What five take did you get from the scenerio?
Something that stuck out to me was the fact that even if you think your first initial work is polished, without cross-checking your work, you can never be sure.
* How does the weekly topic relate to the MIM model?
This week particularly coincides with the 'consciousness aspect of the MIM model, as even though we may feel like we are self-aware, we need to do our best to review our work, thoughts, and actions.
* 20 pts Questions Cognitive: (Wow, I learn?... Ok that is deep!)
* Why is this week's topic important for teamwork?
This week's topic directly related to teamwork because we were assigned teamates for our acorn projects.
* How do plan on contributing to the team, besides completing your tasks?
I plan on contributing to the team by making a group chat and communicating a time where we can meet to work on next week's project.
* How does your experience relate to other experiences you have had?
My experience relates to other experiences because I've been assigned many group projects in the past.
* How does your experience relate to other classmates’ experiences?
My experience relates because one of my classmates also has had to take initiative in gathering classmates to finish a task.
* Tell me about what you taught someone? And what did they learn, that they didn’t know before?
* If you were to write your experience as STAR story, how would you phrase it?
One experience I can recall is when I taught someone about what we learned, they brought up the fact that everyone is more of an agreeable person than they actually are. This allowed me to humble myself and focus more on my weaknesses. This led my team to follow my example and acknowledge their weaknesses, and thus from this experience we were able to grow closer together from that humility.
* If this was a religion class, how would you relate this week’s topic to the gospel?
I would phrase it like 'Humility breeds excellence'. If you think about it, this relates well with the saviors example. If we follow his example and humble ourselves, we can learn and grow a lot more.
