#+title: cse170 - wk05 refleciton
#+Author: Daniel Gomez
#+Date: 05/20/22

/TOTAL POINTS: 100/100/

5 pts Questions             Affect: (What?, So What?...Return, Report, Reflect and Regroup.)
What? (Return and Report)
* What did I do to prepare for class this week?
I did all of the assigned reading and researched all of the topics, including completing the personality test

* What evidence can I provide that demonstrates with affirmation statements?
The following link to my work: <https://github.com/danielgomez3/cse170_repo/blob/main/personalproject.org>, and also, *My personality type is Architect INTJ-A/INTJ-T*

* What concept from this week are you uncertain of or would like to know more about?
Maybe wanting to know more of a background of the personality test, how it came to fruition, and why I should put trust into it.

* What topics were studied this week, and what are their definitions?
The topics we studied this week included how to be a professional for today's workforce, guides to professionalism. *Professionalism* means competence or skill expected of a professional.

* What phase of your projects did you complete?
I completed all phases, including putting my work on Github.

* In your team meeting, what where the answers to this week’s questions?
In our team meeting many people shared their personality types. We also tried to answer questions about the test itself.

* Summarize this week’s scenerio?
This week's scenario was spent working on our personal projects

* Where did you put your assigments in GitHub?
<https://github.com/danielgomez3/cse170_repo>


* So What? (Reflect and Regroup) What did I learn from the study material
I learned that professionalism is important in the workplace because it encourages others to be accountable. When we are professional, we lead by example and promote good.

* Why is this week's topic important?
This week's topic is important because if we work on being professional now, we will hopefully develop a mastery for the future.

* How did this week scenerio relate to the week’s topic?
This week's personal project related to this week but I mainly saw it relate to last-week's topic because we spent a lot of time on personality. Being aware of our personality types can help use gain a general idea of in what areas we might need more work done.

* What did you learn from your work on your project?
I discovered more about my personality and weakness. I learned more about what I wanted for communication and more about my strengths and tendencies.

* What insights did your team lean from this week’s questions?
This week my team had similar insights, and we tried to figure out which personalities matched better with others.

* What actions were assigned to you, in your team meeting?
We were only supposed to work on our personal projects this week

* 10 pts Questions Behavior: (What now?...my ideas are starting to emerge!) What is the most significant take-a-way you have gained from your study this week?
My most significant take-a-way was that we're supposed to do our best to develop professionalism during our time in school so we can be prepared for the workplace

* What do you do, steps, or processes related to this week's topic?
I searched and read articles what it meant to be professional

* How would you explain this week's topics to a person not in this class?
The best way I would explain it: Professionalism refers to the way you represent yourself in a business setting. Most of all, professional behavior is considerate, formal, and focused.

* What did you learn by explaining this week's topic to someone not in this class?
The topic was something they understood. My wife was personally interested however with the 16-type personality test, and I feel this is pretty indicative with our obsession these days in personality tests and star-signs, etc.

* Write a SMART goal for next week?
Complete a sudden-death type-racer at least once with 60wpm.

* What would you do differently next week?
Next week I would focus on something more realistic and accomplishable versus what I had previously done.

* What five take did you get from the scenerio?
Something that my teacher said that I found interesting was that he said he wasn't a professional, but instead he was just an employee aspiring toward professionalism.

* How does the weekly topic relate to the MIM model?
This week particularly coincides with the 'representation' aspect of the MIM model, as even though we all vary in personality it's still our duty to strive for professionalism and overall excellence.

* 20 pts Questions Cognitive: (Wow, I learn?... Ok that is deep!) Why is this week's topic important for teamwork?
This week's topic is important for teamwork because it only helps us as individuals to discover ourselves and our own personalities.

* How do plan on contributing to the team, besides completing your tasks?
I plan on getting to know their personality types and ask questions that would provoke their good side or interests that their personality type might generally like.

* How does your experience relate to other experiences you have had?
My experience serving a full-time mission really help me realize more-so that each of us were all in fact very different. Some missionaries even expressed strong Progressive political viewpoints and some their more Libertarian. But the work was what in fact pulled us together to achieve a common goal.

* How does your experience relate to other classmates’ experiences?
Many of us still hold and value our differences to this day in spite of serving missions and having very similar objectives, yet we all still cooperate.

* Tell me about what you taught someone? And what did they learn, that they didn’t know before?
I taught someone about morals and the importance of moral-discipline. They didn't really understand the purpose of being morally straight, and they learned more about the Gospel of Jesus Christ in the process.

* If you were to write your experience as STAR story, how would you phrase it?
When I taught somebody about moral-discipline on my 2-year mission, they seemed confused because they claimed that good-behavior and justice was relative to the individual's upbringing. While I affirmed that some of those things were in fact true, the Gospel of Jesus Christ affirms us that there will always be an innate and if not innate, a true right and a wrong that we need to follow and execute. It only befits us doing so.

* If this was a religion class, how would you relate this week’s topic to the gospel?
As I explained earlier, our differences in personality can be seen in the church of Jesus Christ. Even though we might even differ politically, we all are still brought to endure one-another's differences to be professionals.
