
#+options: toc: nil

#+title: Week 8 Reflection
#+subtitle: Points earned: 100/100

5 pts Questions             Affect: (What?, So What?...Return, Report, Reflect and Regroup.)
What? (Return and Report)
** What did I do to prepare for class this week?
*This week I completed all of the necessary activities and readings
** What evidence can I provide that demonstrates with affirmation statements?
*The accuracy of information answered throughout the following questions
** What concept from this week are you uncertain of or would like to know more about?
*I not unfamiliar with any topic.
** What topics were studied this week, and what are their definitions?
*We went more in depth about our user Acorn Project, and finalized it.
** What phase of your projects did you complete?
*We completed all phases and requirements.
** In your team meeting, what where the answers to this week’s questions?
*We discussed and learned how to respond to conflict in the workplace. We learned to say the following (ultimately owning-up to your mistakes):
*1. I would like to aplogize.
*2. I did this, and I can fix this
** Summarize this week’s scenerio?
*This week we studied and read multiple articles on how to resolve team conflict, as well as explore ways in which we could improve our assertive communication.
** Where did you put your assigments in GitHub?
*I put them in my project's README.
* So What? (Reflect and Regroup)
** What did I learn from the study material
This week I learned how to use "I" statements effectively. I learned that an "I" statement is any statement that is simple and clear. It's not about being polite, and it's not about being rude. It's a statement that's unlikely to do harm, and a step in the right direction. It's being humble by being personal an open. Examples were:
"I did this"
"I am sorry"
"I'll get right on it"
** Why is this week's topic important?
It's important because without these skills, we are unlikely to be respected in the workplace, and be hired for future important positions.
** How did this week scenario relate to the week’s topic?
This week's scenario related because we were able to play games and activities like both pulling on each others grips to lift each other physically.
** What did you learn from your work on your project?
I learned again that we needed to keep an open and effective communication in order to maintain good productivity.
** What insights did your team lean from this week’s questions?
We were able to conclude that ultimately those who were humble and direct would be the most respected, and thus prospered the most in the workplace.
** What actions were assigned to you, in your team meeting?
The way we were able to lift up each other physically, can be applied in the same connotation metaphorically when we work together in the workplace.
* 10 pts Questions Behavior: (What now?...my ideas are starting to emerge!)
** What is the most significant take-a-way you have gained from your study this week?
The most significant take-a-way was that even "I" statements and things that are otherwise helpful also have their drawbacks if not used properly. Thus it's important to continue to keep an open mind.
** What do you do, steps, or processes related to this week's topic?
I will be more careful in organizing my words, so that whatever I say, I ultimately keep the goal of being nice, formal, and apologetic when needed. Not overly submissive and sharing.
** How would you explain this week's topics to a person not in this class?
"This week in class we learned how to resolve and address conflict in the workplace. We also learned ways in which we could respond to other's mistakes as to not humiliate them as well as tactics to prevent them from being offended"

** What did you learn by explaining this week's topic to someone not in this class?
I learned that this was mostly an agreeable topic, with a lot of the topic being understood by wife, being a successful graduate.

** Write a SMART goal for next week?
My next SMART goal: continue type-racer on sudden death to improve my workflow.
** What would you do differently next week?
Next week I would attempt to practice some of the principles of effective communication in my own relationship.
** What five take did you get from the scenerio?
My five-take: Although people can be similar, we all interpret things and take offence to things differently.
** How does the weekly topic relate to the MIM model?
Again, what we think of others (if we were to think we were better than others intellectually, for example) greatly impact the way we behave and treat others in real life.
* 20 pts Questions Cognitive: (Wow, I learn?... Ok that is deep!)
** Why is this week's topic important for teamwork?
This week's topic is important for teamwork because we are able to work better with others once we respect and realize the reasons for which others behave, and adjust our behavior accordingly.
** How do plan on contributing to the team, besides completing your tasks?
I plan on reaching out the them and initiation contact, as well as make sure I am apologetic if I've offended any of them in the process of my conduct.
** How does your experience relate to other experiences you have had?
I've had experience where a family member thought I got angry at the or was upset, when in reality I had not idea I did so. So I remember reaching out to them feeling bad for doing so. We were able to laugh at a once awkward situation, and learn from it.
** How does your experience relate to other classmates’ experiences?
Other classmates were able to report the similar experience of hearing second-hand that they offended someone, and the best course of action being reaching out to them, addressing, and apologizing for themselves.
** Tell me about what you taught someone? And what did they learn, that they didn’t know before?
I was able to teach them about my mannerisms, and to feel free to reach out to me if this feeling happened again, so I could maybe explain and correct my conduct so it wouldn't happen again.
** If you were to write your experience as STAR story, how would you phrase it?
In the workplace a few years ago, I had an experience where a co-worker thought I was upset with them. So I remember reaching out to them feeling bad for doing so. We were able to laugh at a once awkward situation, and learn from it.
I was able to teach them about my mannerisms, and to feel free to reach out to me if this feeling happened again, so I could maybe explain and correct my conduct so it wouldn't happen again. It was a silly dispute, and nothing severe happened because we were able to communicate how it happened, and what I could do to make sure it never happened again.
** If this was a religion class, how would you relate this week’s topic to the gospel?
The Savior expects the most from us, behaviorally and even in our thoughts. If our thoughts about others are clean, behaviorally we will reflect that to others.
