Reflection        Name: Daniel Gomez                      Total Points: 100/100

Every other week in this class, you will reflect on your learning. Your participation in the summary is a summation of your answers the following questions. The questions are categorized on the difficulty of depth. Each question you answer is worth that many points; when you are done answering the questions, give yourself a total score based on the rubrics and provide justification in one sentence. You can only use each question once.

Please answer a subset of the following questions:

* 5 pts Questions             Affect: (What?, So What?...Return, Report, Reflect and Regroup.)
* What? (Return and Report)
* What did I do to prepare for class this week?
I prepared our class presentation and gave mostly just my feedback on what needed to change and be done.
* What evidence can I provide that demonstrates with affirmation statements?
The completion of the Acorn Project presentation.

* What concept from this week are you uncertain of or would like to know more about?
There isn't one that comes to mind.
* What topics were studied this week, and what are their definitions?
There was no 'teach' module for this week.

* What phase of your projects did you complete?
Creating drafts for our Acorn Project throughout the week.

* In your team meeting, what where the answers to this week’s questions?
To create good schedules and make deadlines, it's smart to use a schedule on software that doesn't require that many dependencies, and it's helpful to implement KISS (keep it simple, stupid), and write down accomplish able feasible tasks to execute.

* Summarize this week’s scenerio?
There was no scenario given from this week

* Where did you put your assigments in GitHub?
* So What? (Reflect and Regroup)
* What did I learn from the study material
There was no study material for this week
* Why is this week's topic important?
There was no topic for given this week.
* How did this week scenerio relate to the week’s topic?
There was no Scenario given from this week

* What did you learn from your work on your project?
I learned that even though we might not have been 100% succesful in all of our endeavors, we acheived at least some kind of success.

* What insights did your team lean from this week’s questions?
There was no 'TEACH' module given for this week.

* What actions were assigned to you, in your team meeting?
Attend the work conference each week.

* 10 pts Questions Behavior: (What now?...my ideas are starting to emerge!)
The most significant take-a-way I have gained this week: conducting discussions require patient and a constant effort to maintain focus.
* What is the most significant take-a-way you have gained from your study this week?
A significant take-a-way: the best way to be influential in the workplace is by making sure I'm constantly and always living in a way that is inspiring. 


* What do you do, steps, or processes related to this week's topic?
I think the best way to achieve the level of good Leadership takes constant success in practice. Putting ourselves in leadership opportunities or even exercising proper stewardship over what we have will help us to forge better leadership skills.


* How would you explain this week's topics to a person not in this class?
This week we focused on ways in which we could become better leaders, even if we didn't have specific rule over people or an organization. Thus, in a way, becoming better stewards over the things that we own and oversee. That way we possibly show the Lord that we may be trusted with more.

* What did you learn by explaining this week's topic to someone not in this class?
I learned that it the topic applies to everyone, even if they're not in traditional leadership positions.

* Write a SMART goal for next week?
Play Type-Racer on sudden-death mode 4 time (twice the amount of amount of times that I've done before)

* What would you do differently next week?
I would make sure to exact my goals early in the morning after prayer to make sure that I get it done.

* What five take did you get from the scenerio?
From last week, my five-take was looking back on my mission and remembering having some companions and people that I found difficult to agree with, or at least ones that I didn't find myself naturally attracted to be around in a friendly-sense. But like Astrid and Rita, It's important to put those differences aside even if they may bother us to our metaphorical cores.

* How does the weekly topic relate to the MIM model?
Maybe I can share my second-take from last week's scenario: The MIM model works great in this scenario because it really takes patience to process what happens that may happen to us, and taking a minute to process and react in order to make sure we don't do or say things we might regret.

* 20 pts Questions Cognitive: (Wow, I learn?... Ok that is deep!)
* Why is this week's topic important for teamwork?
When giving our presentations, we need to make sure that we're doing everything we can to give space for our teammates to speak and share their thoughts.
* How do plan on contributing to the team, besides completing your tasks?
Our team presentation is done.
* How does your experience relate to other experiences you have had?
This relates to my mission when I had to learn the hard way not to speak over my companions. The lesson will be more fulfilling and go smoother when you do.

* How does your experience relate to other classmates’ experiences?
My experience doing this relates to my time as a Project manager. Sometimes, I failed to deliver what was expected. This alone is okay, only if was able to learn from that experience and do my best to mitigate any further opportunities to fail.

* Tell me about what you taught someone? And what did they learn, that they didn’t know before?
Other classmates felt confident in their ability to succeed and to learn from their mistakes.

* If you were to write your experience as STAR story, how would you phrase it?
There was a time where a friend came to apologize to me and was afraid I wasn't able to forgive him, and my instant inner-reaction was to say: 'It's okay. Don't do it again.'. Although I would learn to strive to put that phrase more lightly in the future, I would frequently use this experience to aim my overall verbage and conclusion for future learning opporunities.


* If this was a religion class, how would you relate this week’s topic to the gospel?
At the end of our lives, when we strive to do what's best and fail, It's okay as long as we learn from what we do and don't do it again. As I mentioned, my attempts at meeting every requirement wasn't spot-on, but that's okay because I know what to do next time I'm presented the opportunity.
