Reflection        Name: Daniel Gomez                      Total Points: 100/100

Every other week in this class, you will reflect on your learning. Your participation in the summary is a summation of your answers the following questions. The questions are categorized on the difficulty of depth. Each question you answer is worth that many points; when you are done answering the questions, give yourself a total score based on the rubrics and provide justification in one sentence. You can only use each question once.

Please answer a subset of the following questions:

5 pts Questions             Affect: (What?, So What?...Return, Report, Reflect and Regroup.)
What? (Return and Report)
* What did I do to prepare for class this week?
I read all of the assigned readings as well as watched the entire TED talks.
* What evidence can I provide that demonstrates with affirmation statements?
The answers to the following questions.
* What concept from this week are you uncertain of or would like to know more about?
There are none.
* What topics were studied this week, and what are their definitions?
Synergistic Communication: 
Opening your mind and heart and expressions to new possibilities, alternatives, and options. 
* What phase of your projects did you complete?
All phases of the Acorn project are complete.
* In your team meeting, what where the answers to this week’s questions?
There was no teach module.
* Summarize this week’s scenerio?
This week's scenario revolved around a TED Talk given by Amy Edmondson and her
* Where did you put your assigments in GitHub?
Here on this Github page.
* So What? (Reflect and Regroup)
* What did I learn from the study material
I learned that teamwork on the fly is what's known as 'Teaming', regardless of expertise, cultural background, or agency.
* Why is this week's topic important?
Professional Culture clash can happen in any profession that involves teamwork (pretty much every profession), so it's important to be mindful of that in order to counteract it.

* How did this week scenerio relate to the week’s topic?
Professional culture-clash is one of the biggest obstacles big companies and industries are trying to fix.

* What did you learn from your work on your project?
I learned that even though we might not have been 100% successful in all of our endeavors, we achieved at least some kind of success.

* What insights did your team lean from this week’s questions?
There was no 'TEACH' module given for this week.
* What actions were assigned to you, in your team meeting?
Deliver the deliverables for the Acorn Project.
* 10 pts Questions Behavior: (What now?...my ideas are starting to emerge!)
* What is the most significant take-a-way you have gained from your study this week?
Teamwork as a Software Engineer will most likely take work across multiple different fields, and so it's most important to master the concept of teaming so we can achieve large worth-while projects.

* What do you do, steps, or processes related to this week's topic?
I personally will seek to put aside differences and pair similarities with the ones I work with.

* How would you explain this week's topics to a person not in this class?
One of the greatest difficulties of teamwork has to do with culture clash, but learning to put those aside to work on an important and common goal will result in Teaming.
Teamwork on the fly is what's known as 'Teaming', regardless of expertise, cultural background, or agency.

* What did you learn by explaining this week's topic to someone not in this class?
I learned that 'Teaming' was a topic that my graduate wife had personally heard of before, but didn't recognize the name. Because of the fact that she already was familiar, it was easy for her to grasp the concept and agree with its definition.
* Write a SMART goal for next week?
Play Type-Racer on sudden-death mode 4 time (twice the amount of amount of times that I've done before).
* What would you do differently next week?
I would make sure to exact my goals early in the morning after prayer to make sure that I get it done.
* What five take did you get from the scenerio?
To be curious about everything. Be humble. That will ensure that I'm able to complete my job with proficiency.
* How does the weekly topic relate to the MIM model?
It's hard for others to participate in teamwork together when we don't follow the MIM model, and we internalize that everybody around us is a competitor.
* 20 pts Questions Cognitive: (Wow, I learn?... Ok that is deep!)
* Why is this week's topic important for teamwork?
This week's topic is important for teamwork because teaming will not only allow us to become more hireable, it will ultimately make us become more desirable as people, so people around us may appreciate our contributing presence more.
* How do plan on contributing to the team, besides completing your tasks?
I will plan on meeting with my teammates one last time to do some networking and follow-ups to maintain my relationship with them.
* How does your experience relate to other experiences you have had?
I've had experience where a family member thought I got angry at the or was upset, when in reality I had not idea I did so. So I remember reaching out to them feeling bad for doing so. We were able to laugh at a once awkward situation, and learn from it.
* How does your experience relate to other classmates’ experiences?
Other classmates were able to report the similar experience of hearing second-hand that they offended someone, and the best course of action being reaching out to them, addressing, and apologizing for themselves.
* Tell me about what you taught someone? And what did they learn, that they didn’t know before?
I was able to teach them about my mannerisms, and to feel free to reach out to me if this feeling happened again, so I could maybe explain and correct my conduct so it wouldn't happen again.
* If you were to write your experience as STAR story, how would you phrase it?
In the workplace a few years ago, I had an experience where a co-worker thought I was upset with them. So I remember reaching out to them feeling bad for doing so. We were able to laugh at a once awkward situation, and learn from it.
I was able to teach them about my mannerisms, and to feel free to reach out to me if this feeling happened again, so I could maybe explain and correct my conduct so it wouldn't happen again. It was a silly dispute, and nothing severe happened because we were able to communicate how it happened, and what I could do to make sure it never happened again.
* If this was a religion class, how would you relate this week’s topic to the gospel?
The Savior expects the most from us, behaviorally and even in our thoughts. If our thoughts about others are clean, behaviorally we will reflect that to others. So ultimately, if we come closer to Christ (even by obeying the commandments), we may become just like him, who is /the/ ultimate 'Teamer'.
